import Link from "next/link";
export default function Home() {
 return <main className="home-container">
  <nav className="flex flex-wrap items-center justify-between gap-4 py-4" aria-label="Public navigation"><Link href="/" className="mira-wordmark">MIRA</Link><div className="flex gap-2"><Link href="/auth/login" className="button-ghost">Log in</Link><Link href="/auth/sign-up" className="button-primary">Get started</Link></div></nav>
  <section className="home-hero"><h1>Help your child learn.<br />Know where to start.</h1><p>MIRA helps you choose experiences that fit your child and your family. Find out what you need, how to take part, and what you might notice along the way.</p><div className="flex flex-wrap gap-3"><a href="#approach" className="button-ghost">Get to know MIRA</a><Link href="/auth/sign-up" className="button-primary">Create an account</Link></div></section>
  <section id="approach" className="home-section"><h2>A plan you can make your own</h2><p className="workspace-description mb-10">Start with your hopes, the people in your child’s life, and the time you have. Bring languages, stories, play and everyday routines into the same plan.</p><div className="home-steps"><div><h3>What matters to you?</h3><p>Share your priorities and what fits at home. You can leave optional questions for later.</p></div><div><h3>See the purpose and preparation</h3><p>Understand your role before you put the screen away. Repeat, change or skip an experience.</p></div><div><h3>Use what you notice</h3><p>A short observation can help with the next plan. Your child’s response stays an observation, not a label.</p></div></div></section>
  <section className="home-section"><h2>Support for you. Experiences with your child.</h2><p className="workspace-description">MIRA is for parents and caregivers. It is not a child-facing chatbot, a developmental assessment, or a list of lessons your family has to finish.</p><details className="mt-8"><summary className="cursor-pointer py-3">Where does AI fit?</summary><p className="workspace-description mt-3">Guide can help you think through a question. Profile suggestions are yours to review before saving. AI can get things wrong; it does not assess your child or make parenting decisions for you.</p></details></section>
  <footer className="home-section flex flex-wrap justify-between gap-4 text-sm text-muted-foreground"><span>MIRA · Made for family life</span><Link href="/auth/sign-up" className="underline">Create an account</Link></footer>
 </main>;
}
